package tempura.cozy
import tempura.cozy.Transforms.*
/////////////////////////////
/** AUTO-GENERATED BY SBT **/
object Registry {
  private val storage: Map[String, Transform[? <: Tuple, ? <: Tuple]] = Map(
    "c-mine-index-term" -> tempura.liveness.IndexTermMiner,
    "c-synth-rel-ranking" -> tempura.liveness.RelationalRankingSynthesizer,
    "c-read-vmt" -> tempura.parsing.io.VMTReader,
    "c-read-string" -> tempura.parsing.io.StringReader,
    "c-read-tdl" -> tempura.parsing.io.TDLReader,
    "c-path-of" -> tempura.parsing.io.PathOf,
    "c-read-sexpr" -> tempura.parsing.io.SexprReader,
    "c-print-tdl" -> tempura.parsing.printers.TDLPrinter,
    "c-print-smtlib" -> tempura.parsing.printers.FormulaPrinter,
    "c-parse-sexpr" -> tempura.parsing.sexpr.StringToSExprParser,
    "c-parse-smtlib" -> tempura.parsing.sexpr.SmtlibParser,
    "c-parse-vmt" -> tempura.parsing.sexpr.VMTParser
  )

  def lookup(name: String): Option[Transform[? <: Tuple, ? <: Tuple]] = storage.get(name)

  def getAllTransforms: Map[String, Transform[? <: Tuple, ? <: Tuple]] = storage
  def getAs[T](name: String): Option[T] =
    storage.get(name).map(_.asInstanceOf[T])
}
